<?php
/*

lang-simplified_chinese.php
===============
Pixelpost version 1.6

SVN file version:
$Id$

Language file: english/default
edited and added to the version 1.4-pack by by Connie M黮ler-G鰀ecke

Pixelpost www: http://www.pixelpost.org/

Version 1.5:
Development Team:
Ramin Mehran, Connie Mueller-Goedecke, Will Duncan, Joseph Spurling, Piotr "GeoS" Galas
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright ?2006 Pixelpost.org <http://www.pixelpost.org>


License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'The PixelPost Crew';
$_lang_file_email             = 'thecrew@pixelpost.org';
$_lang_file_rev               = '1.0.0';

// IMAGE NAVIGATION
$lang_previous                    = "&laquo;";
$lang_next                        = "&raquo;";
$lang_no_previous                 = "没有上一张图片";
$lang_no_next                     = "没有下一张图片";
$lang_latest									 = "Last";
$lang_first										 = "First";
$lang_browse_select_category      = "选择类别";
$lang_browse_all                  = "全部";
$lang_permalink                   = "永久连接";
$lang_paged_archive						= "Archive";

// COMMENTS
$lang_message_missing_image      = "没有选取图片。评论没有保存。";
$lang_message_missing_comment    = "没有输入信息。评论没有保存。";
$lang_message_missing_name       = "没有输入名字。评论没有保存。";
$lang_message_moderating_comment = "已经收到您的评论！管理员检视后就会发布。";
$lang_visit_homepage             = "浏览首页";
$lang_no_comments_yet            = "暂时还没有评论。";
$lang_comment_thank_you          = "感谢您的访问以及花时间评论相片。现在将会返回刚才的页面。";
$lang_comment_redirect           = "如果浏览器没有自动返回，请点击返回。";
$lang_comment_redirect_error     = "评论发送错误！如果浏览器没有自动返回，请点击返回。";
$lang_comment_page_title         = "评论";
$lang_comment_popup              = "评论";
$lang_comment_plural						 = "Comments";
$lang_comment_single						 = "Comment";


// EXIF DATA
$lang_exposure                   = "快门:";
$lang_aperture                   = "光圈:";
$lang_capture_date               = "拍摄时间:";
$lang_focal                      = "焦距:";
$lang_camera_maker               = "相机生产商:";
$lang_camera_model               = "相机型号:";
$lang_flash_fired                = "闪光:有";
$lang_flash_not_fired            = "闪光:没有";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "类别:";
$lang_category_plural            = "类别:";

// Month and Day
$lang_monday                     = "一";
$lang_tuesday                    = "二";
$lang_wednesday                  = "三";
$lang_thursday                   = "四";
$lang_friday                     = "五";
$lang_saturday                   = "六";
$lang_sunday                     = "日";

$lang_january                   = "一月";
$lang_february                  = "二月";
$lang_march                     = "三月";
$lang_april                     = "四月";
$lang_may                       = "五月";
$lang_june                      = "六月";
$lang_july                      = "七月";
$lang_august                    = "八月";
$lang_september                 = "九月";
$lang_october                   = "十月";
$lang_november                  = "十一月";
$lang_december                  = "十二月";

// newly added
$lang_message_banned_comment     = "您的评论没有保存！因里面含有禁止使用的语句或电子邮件。";
$lang_comment_popup_disabled     = "Commenting on this picture has been disabled";
$lang_tags                       = "Tags:<br/>";

// Alternative language
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Français";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Português";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Español";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish						="Dansk";

// Email Notification

$lang_email_notification_subject = "新评论";
$lang_email_notification_pt1 = "
	  您好,<br>
      网站有新的评论。<br><br>
	  ";
$lang_email_notification_pt2 = "
      <br>
      以下是评论：<br>
      ----------------------------------------------------------------------<br>
	  ";
$lang_email_notification_pt3 = "来自";
$lang_email_notification_pt4 = "
            ----------------------------------------------------------------------    <br>
      电子邮件发自pixelpost<br>
";
$lang_email_notificationplain_pt1 = "
	  您好,
      网站有新的评论。";
$lang_email_notificationplain_pt2 = "
      以下是评论：
      ----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "来自";
$lang_email_notificationplain_pt4 = "
      ----------------------------------------------------------------------
      电子邮件发自pixelpost
";
$lang_spamflood										= "Comment flood protection is enabled. You need to wait <TIME_TO_WAIT> minutes before posting another comment.";

// RSS & ATOM Feed
$lang_comment_feed_title        = "Newest comments on";
$lang_comment_feed_image_title  = "New comment on";
?>