<?php
/*

lang-norwegian.php
===============
Pixelpost version 1.6

SVN file version:
$Id$

Language file: norwegian
edited and added to the version 1.4.3-pack by Torkel Guttormsen

Version 1.5:
Development Team:
Ramin Mehran, Connie Mueller-Goedecke, Will Duncan, Joseph Spurling, Piotr "GeoS" Galas
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Copyright  2006 Pixelpost.org <http://www.pixelpost.org>
Copyright (c) 2004 shapestyle graphic design + code <http://www.shapestyle.se>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org


______________________________________________________________________________
License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                   ||  Edit                                                        */

$_lang_file_translator        = 'Torkel Guttormsen';
$_lang_file_email             = 'thecrew@pixelpost.org';
$_lang_file_rev               = '1.4.3';

// IMAGE NAVIGATION
$lang_previous                   = "Forrige";
$lang_next                      = "Neste";
$lang_no_previous               = "Ingen tidligere bilder";
$lang_no_next                   = "Ingen flere bilder";
$lang_latest									 = "Last";
$lang_first										 = "First";
$lang_browse_select_category    = "Velg kategori";
$lang_browse_all                = "Alle";
$lang_paged_archive							= "Archive";

// COMMENTS
$lang_message_missing_image     = "Inget bilde var valgt, kommentaren ble ikke lagret.";
$lang_message_missing_comment   = "Ingen beskjed gitt. Kommentaren ble ikke lagret.";
$lang_visit_homepage            = "Bes&oslash;k hjemmeside";
$lang_no_comments_yet           = "Ingen kommentarer forel&oslash;pig.";
$lang_comment_thank_you         = "Takk for kommentaren.";
$lang_comment_redirect          = "Klikk for &aring; g&aring; tilbake.";
$lang_message_moderating_comment = "Your comment is received! It will become public after authorizing by photoblog admin.";
$lang_comment_redirect_error    = "Comment submition error! Please click to be transferred back, if redirection doesn't work";
$lang_comment_page_title        = "Kommentar";
$lang_comment_popup             = "Kommentarer";
$lang_message_banned_comment    = "Your comment is not saved! It contains one or more banned words/email/ips.";
$lang_comment_popup_disabled    = "Commenting on this picture has been disabled";
$lang_comment_plural						= "Comments";
$lang_comment_single						= "Comment";
$lang_tags                      = "Tags:<br/>";

// EXIF DATA
$lang_exposure              = "Lukkertid:";
$lang_aperture              = "Blender:";
$lang_capture_date          = "Dato:";
$lang_focal                 = "Fokus:";
$lang_camera_maker          = "Kameraprodusent:";
$lang_camera_model          = "Kameramodell:";
$lang_flash_fired           = "Blitz: Ja";
$lang_flash_not_fired       = "Blitz: Nei";
$lang_flash_not_detected         = "Flash: Not Detected";
$lang_iso                   = "ISO:";

// Category
$lang_category_singular	   = "Kategori:";
$lang_category_plural      = "Kategorier:";

// Month and Day
$lang_monday              = "mandag";
$lang_tuesday             = "tirsdag";
$lang_wednesday           = "onsdag";
$lang_thursday            = "torsdag";
$lang_friday              = "fredag";
$lang_saturday            = "l&oslash;rdag";
$lang_sunday              = "s&oslash;ndag";

$lang_january             = "januar";
$lang_february            = "februar";
$lang_march               = "mars";
$lang_april               = "april";
$lang_may                 = "mai";
$lang_june                = "juni";
$lang_july                = "juli";
$lang_august              = "august";
$lang_september           = "september";
$lang_october             = "oktober";
$lang_november            = "november";
$lang_december            = "desember";

// Alternative language
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Français";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Português";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Español";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish						="Dansk";

// Email Notification

$lang_email_notification_subject = "New Comment";
$lang_email_notification_pt1 = "Hello,<br>A new comment has been made at your photoblog.<br><br>";
$lang_email_notification_pt2 = "<br>The comment is: <br>----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "by";
$lang_email_notification_pt4 = "\n\n----------------------------------------------------------------------    <br>\n\nEmail sent by Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Hello,\n\nA new comment has been made at your photoblog.";
	$lang_email_notificationplain_pt2 = "\n\nThe comment is:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "by";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail sent by Pixelpost";
// Error Message
$lang_nothing_to_show             = "Coming Soon! Nothing to show. No image to show here!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Comment flood protection is enabled. You need to wait <TIME_TO_WAIT> before posting another comment.";



// RSS & ATOM Feed
$lang_comment_feed_title        = "Newest comments on";
$lang_comment_feed_image_title  = "New comment on";
?>