<?php
/*

lang-japanese.php
===============
Pixelpost version 1.6

SVN file version:
$Id$

Language file: Japanese
Author:  Mitsuhiro Yoshida - http://mitstek.com/

Version 1.5:
Development Team:
Ramin Mehran, Connie Mueller-Goedecke, Will Duncan, Joseph Spurling, Piotr "GeoS" Galas
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright  2006 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki:     http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org


License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'Mitsuhiro Yoshida - <a href="http://mitstek.com/" target="_blank">mitstek.com</a>';
$_lang_file_email             = 'thecrew@pixelpost.org';
$_lang_file_rev               = '1.5';

// IMAGE NAVIGATION
$lang_previous                    = "前へ";
$lang_next                        = "次へ";
$lang_no_previous                 = "前のイメージはありません。";
$lang_no_next                     = "次のイメージはありません。";
$lang_browse_select_category      = "カテゴリを選択してください";
$lang_browse_all                  = "すべて";
$lang_permalink                   = "パーマリンク";
$lang_paged_archive               = "アーカイブ";

// COMMENTS
$lang_message_missing_image      = "イメージが選択されていません。コメントは保存されませんでした。";
$lang_message_missing_comment    = "メッセージが入力されていません。コメントは保存されませんでした。";
$lang_message_missing_name       = "氏名が入力されていません。コメントは保存されませんでした。";
$lang_message_moderating_comment = "あなたのコメントが受け付けられました! photoblog管理者の承認後、コメントは公開されます。";
$lang_visit_homepage             = "ホームページを訪問する";
$lang_no_comments_yet            = "まだコメントはありません。";
$lang_comment_thank_you          = "訪問および写真へのコメントを投稿して頂きましてありがとうございます。このページをリダイレクトします。";
$lang_comment_redirect           = "リダイレクトが正常に動作しない場合、ここをクリックして元の画面に戻ってください。";
$lang_comment_redirect_error     = "コメント投稿エラー! リダイレクトが正常に動作しない場合、ここをクリックして元の画面に戻ってください。";
$lang_comment_page_title         = "コメント";
$lang_comment_popup              = "コメント";
$lang_comment_popup_disabled     = "この写真に対するコメントは無効にされています。";
$lang_comment_plural						 = "Comments";
$lang_comment_single						 = "Comment";


// EXIF DATA
$lang_exposure                   = "露出:";
$lang_aperture                   = "絞り:";
$lang_capture_date               = "撮影日時:";
$lang_focal                      = "焦点:";
$lang_camera_maker               = "カメラメーカー:";
$lang_camera_model               = "カメラモデル:";
$lang_flash_fired                = "フラッシュ: 使用";
$lang_flash_not_fired            = "フラッシュ: 未使用";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "カテゴリ:";
$lang_category_plural            = "カテゴリ:";

// Month and Day
$lang_monday                     = "月";
$lang_tuesday                    = "火";
$lang_wednesday                  = "水";
$lang_thursday                   = "木";
$lang_friday                     = "金";
$lang_saturday                   = "土";
$lang_sunday                     = "日";

$lang_january                   = "1";
$lang_february                  = "2";
$lang_march                     = "3";
$lang_april                     = "4";
$lang_may                       = "5";
$lang_june                      = "6";
$lang_july                      = "7";
$lang_august                    = "8";
$lang_september                 = "9";
$lang_october                   = "10";
$lang_november                  = "11";
$lang_december                  = "12";

// newly added
$lang_message_banned_comment     = "あなたのコメントは保存されませんでした! 1つまたはそれ以上の使用禁止用語/メールアドレス/IPアドレスを含んでいます。";
$lang_tags                       = "タグ:<br/>";

// Alternative language
$lang_alt_lang_dutch              ="Nederlands";
$lang_alt_lang_english            ="English";
$lang_alt_lang_french             ="Francais";
$lang_alt_lang_german             ="Deutsch";
$lang_alt_lang_italian            ="Italiano";
$lang_alt_lang_japanese           ="Japanese";
$lang_alt_lang_norwegian          ="Norsk";
$lang_alt_lang_persian            ="Farsi";
$lang_alt_lang_polish             ="Polski";
$lang_alt_lang_portuguese         ="Portugues";
$lang_alt_lang_simplified_chinese ="Chinese";
$lang_alt_lang_spanish            ="Espanol";
$lang_alt_lang_swedish            ="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish						="Dansk";

// Email Notification

$lang_email_notification_subject = "新しいコメントが投稿されました。";
$lang_email_notification_pt1 = "こんにちは、<br />あなたのphotoblogに新しいコメントが投稿されました。<br /><br />";
$lang_email_notification_pt2 = "<br />コメントは: <br /> ----------------------------------------------------------------------<br />";
$lang_email_notification_pt3 = "by";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br />\n\nEmail sent by Pixelpost<br />";
$lang_email_notificationplain_pt1 = "こんにちは、\nあなたのphotoblogに新しいコメントが投稿されました。";
$lang_email_notificationplain_pt2 = "\n\nコメントは:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "by";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail sent by Pixelpost";

// Error message
$lang_nothing_to_show             = "Coming Soon! 表示するイメージはありません!";
$lang_spamflood										= "Comment flood protection is enabled. You need to wait <TIME_TO_WAIT> minutes before posting another comment.";
?>