<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-german.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________

Die SPRACHDATEI-VARIABLEN:

Linke Seite: Nichts aendern!      ||    rechte Seite: aendern, wenn gewuenscht */

$_lang_file_translator        = 'Marek Nierychlo - <a href="http://lichtlauschen.mareknierychlo.de/" target="_blank">lichtlauschen</a>';
$_lang_file_email             = 'mareknierychlo@gmail.com';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                    = "zur&uuml;ck";
$lang_next                        = "weiter";
$lang_no_previous                 = "keine weiteren Bilder";
$lang_no_next                     = "keine neueren Bilder";
$lang_latest									 = "Letztes";
$lang_first										 = "Erstes";
$lang_browse_select_category      = "Kategorie w&auml;hlen";
$lang_browse_all                  = "alle";
$lang_permalink			          = "Permalink";
$lang_paged_archive						= "Archive";

// COMMENTS
$lang_message_missing_image    = "Kein Bild ausgew&auml;hlt. Der Kommentar wurde nicht gespeichert.";
$lang_message_missing_comment  = "Kein Text eingegeben. Der Kommentar wurde nicht gespeichert.";
$lang_visit_homepage           = "Zur Startseite";
$lang_no_comments_yet          = "Noch keine Kommentare.";
$lang_message_moderating_comment = "Ihr Kommentar wurde gespeichert! Nach der Freigabe wird er auf der Seite angezeigt werden.";
$lang_comment_thank_you        = "Danke dass Sie sich Zeit f&uuml;r einen Kommentar genommen haben.<br>\n\nSie werden nach 5 Sekunden zur&uuml;ckgeleitet.";
$lang_comment_redirect         = "Klicken Sie hier um zur&uuml;ckzukehren";
$lang_comment_redirect_error   = "Kommentar konnte nicht eingetragen werden. Klicken Sie hier, um zur&uuml;ck zur Eingabe zu kommen, falls die automatische Umleitung nicht funktioniert.";
$lang_comment_page_title       = "Kommentar";
$lang_comment_popup            = "Kommentare";
$lang_message_banned_comment   = "Ihr Kommentar wurde nicht gespeichert, da er Worte, E-Mmail-Adressen oder IP-Adressen enth&auml;lt, die in Ban-Listen vorkommen.";
$lang_comment_popup_disabled   = "Die Kommentarfunktion wurde f&uuml;r dieses Bild ausgeschaltet.";
$lang_comment_plural						 = "Kommentare";
$lang_comment_single						 = "Kommentar";
$lang_tags                     = "Tags:<br/>";
$lang_none                       = "keine";

// EXIF DATA
$lang_exposure              = "Verschlusszeit:";
$lang_aperture              = "Blende:";
$lang_capture_date          = "Aufnahmedatum:";
$lang_focal                 = "Fokus:";
$lang_camera_maker          = "Hersteller:";
$lang_camera_model          = "Kamera-Modell:";
$lang_flash_fired           = "Blitz:";
$lang_flash_not_fired       = "Kein Blitz";
$lang_flash_not_detected         = "Blitz: Keine Blitz erkannt";
$lang_iso		            = "ISO:";

// Category
$lang_category_singular	   = "Kategorie:";
$lang_category_plural      = "Kategorien:";


// Month and Day
$lang_monday              = "Montag";
$lang_tuesday             = "Dienstag";
$lang_wednesday           = "Mittwoch";
$lang_thursday            = "Donnerstag";
$lang_friday              = "Freitag";
$lang_saturday            = "Samstag";
$lang_sunday              = "Sonntag";

$lang_january             = "Januar";
$lang_february            = "Februar";
$lang_march               = "M&auml;rz";
$lang_april               = "April";
$lang_may                 = "Mai";
$lang_june                = "Juni";
$lang_july                = "Juli";
$lang_august              = "August";
$lang_september           = "September";
$lang_october             = "Oktober";
$lang_november            = "November";
$lang_december            = "Dezember";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";

// Email Notification

$lang_email_notification_subject = "Neuer Kommentar";
$lang_email_notification_pt1 = "Hallo,<br>ein neuer Kommentar wurde in Ihrem Fotoblog eingetragen.<br><br>";
$lang_email_notification_pt2 = "<br>Kommentartext<br>----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "abgegeben von";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>diese Mail wurde von Pixelpost automatisch versandt<br>";

// Benachrichtigungstext in reinem Textformat:
// Damit der Text richtig umbrochen wird, ist es notwendig, ab und an einen Zeilenumbruch
// einzubinden. Dazu wird "\n" genutzt.
// Achten Sie bitte darauf, diese Sonderzeichen beizubehalten

$lang_email_notificationplain_pt1 = "Hallo,\nein neuer Kommentar wurde in Ihrem Photoblog zu diesem Eintrag abgegeben";
$lang_email_notificationplain_pt2 = "\n\nKommentartext:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "abgegeben von";
$lang_email_notificationplain_pt4 = "\n\n---------------------------------------------------------------------- \n\ndies ist eine von Pixelpost automatisch erstellte Benachrichtigung";

// Error Message
$lang_nothing_to_show             = "Das Fotoblog enth&auml;lt noch keine Bilder. Kommen Sie sp&auml;ter noch Mal vorbei!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Schutz vor Spam-Flut ist aktiviert! Sie m&uuml;ssen <TIME_TO_WAIT> warten, bis Sie einen neuen Kommentar abgeben k&ouml;nnen.";

// RSS & ATOM Feed
$lang_comment_feed_title        = "Neueste Kommentare in";
$lang_comment_feed_image_title  = "Neuer Kommentar f&uuml;r";

// Ende der Sprachdatei
?>