<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-hungarian.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                     ||  Edit                                                        */

$_lang_file_translator		 = 'Soós Zoltán - <a href="hhtp://usualsubjects.com">usualsubjects.com</a>';
$_lang_file_email             	 = 'zoltan[at]usualsubjects.com';
$_lang_file_rev                  = '1.7';

// IMAGE NAVIGATION
$lang_previous                   = "Előző";
$lang_next                       = "Következő";
$lang_no_previous                = "Nincs előző kép";
$lang_no_next                    = "Nincs következő kép";
$lang_latest			 = "Utolsó";
$lang_first		  	 = "Első";
$lang_browse_select_category     = "Válassz kategóriát";
$lang_browse_all                 = "Összes";
$lang_permalink                  = "Permalink";
$lang_paged_archive		 = "Archívum";

// COMMENTS
$lang_message_missing_image      = "Nem választottál képet. A megjegyzést nem mentettük.";
$lang_message_missing_comment    = "Üres a szövegmező. A megjegyzést nem mentettük.";
$lang_message_missing_name       = "Nem adtad meg a neved. A megjegyzést nem mentettük.";
$lang_message_moderating_comment = "A megjegyzésed megkaptuk! Az adminisztrátor ellenőrzi, aztán közzétesszük.";
$lang_visit_homepage             = "Vissza a főoldalra";
$lang_no_comments_yet            = "Nincs megjegyzés.";
$lang_comment_thank_you          = "Köszönjük a látogatást és a megjegyzést. Most átirányítunk.";
$lang_comment_redirect           = "Ha az átirányítás nem működne, kattints ide.";
$lang_comment_redirect_error     = "Hiba a megjegyzés feldolgozása közben! Ha az átirányítás nem működne, kattints ide.";
$lang_comment_page_title         = "Megjegyzés";
$lang_comment_popup              = "Megjegyzések";
$lang_comment_popup_disabled     = "Ehhez a képhez nem fűzhetsz megjegyzést.";
$lang_comment_plural		 = "Megjegyzés";
$lang_comment_single		 = "Megjegyzés";

// EXIF DATA
$lang_exposure                   = "Záridő:";
$lang_aperture                   = "Blende:";
$lang_capture_date               = "Képdátum:";
$lang_focal                      = "Fókusztáv:";
$lang_camera_maker               = "Gyártó:";
$lang_camera_model               = "Modell:";
$lang_flash_fired                = "Vaku: villant";
$lang_flash_not_fired            = "Vaku: nem villant";
$lang_flash_not_detected         = "Vaku: nincs";
$lang_iso                        = "Érzékenység:";

// Category
$lang_category_singular          = "Kategória:";
$lang_category_plural            = "Kategóriák:";

// Month and Day
$lang_monday                     = "hétfő";
$lang_tuesday                    = "kedd";
$lang_wednesday                  = "szerda";
$lang_thursday                   = "csütörtök";
$lang_friday                     = "péntek";
$lang_saturday                   = "szombat";
$lang_sunday                     = "vasárnap";

$lang_january                   = "január";
$lang_february                  = "február";
$lang_march                     = "március";
$lang_april                     = "április";
$lang_may                       = "május";
$lang_june                      = "június";
$lang_july                      = "július";
$lang_august                    = "augusztus";
$lang_september                 = "szeptember";
$lang_october                   = "október";
$lang_november                  = "november";
$lang_december                  = "december";

// newly added
$lang_message_banned_comment    = "A megjegyzésedet nem mentettük, mert tiltott elemeket tartlamaz!";
$lang_tags                      = "Tag-ek:<br/>";
$lang_none                      = "nincs";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch				="Nederlands";
$lang_alt_lang_english				="English";
$lang_alt_lang_french				="Fran&ccedil;ais";
$lang_alt_lang_german				="Deutsch";
$lang_alt_lang_italian				="Italiano";
$lang_alt_lang_norwegian			="Norsk";
$lang_alt_lang_persian				="Farsi";
$lang_alt_lang_polish				="Polski";
$lang_alt_lang_portugues			="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish				="Espa&ntilde;ol";
$lang_alt_lang_swedish				="Svenska";
$lang_alt_lang_japanese				="Japanese";
$lang_alt_lang_danish				="Dansk";
$lang_alt_lang_romanian 			="Romana";
$lang_alt_lang_hungarian			="Magyar";

// Email Notification

$lang_email_notification_subject = "Új üzenet";
$lang_email_notification_pt1 = "Szevasz,<br>új megjegyzés érkezett as fotóblogodra.<br><br>";
$lang_email_notification_pt2 = "<br>A megjegyzés az alábbi: <br> ----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "feladó";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\nEzt a levelet a Pixelpost küldte<br>";
$lang_email_notificationplain_pt1 = "Szevasz,\nÚj megjegyzés érkezett as fotóblogodra.";
$lang_email_notificationplain_pt2 = "\n\nA megjegyzés az alábbi:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "feladó";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEzt a levelet a Pixelpost küldte";

// Error message
$lang_nothing_to_show             = "Nem sokára lesz itt valami, de még nincs...";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood			  = "Túl gyors vagy, várj egy kicsit. Hagyj egy kis időt (<TIME_TO_WAIT>) mielött új megjegyzést küldesz.";


// RSS & ATOM Feeds
$lang_comment_feed_title        = "A legújabb megjegyzések egy képről, melynek címe";
$lang_comment_feed_image_title  = "Új megjegyzés, a kép címe:";
?>
