<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-swedish.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
BEGIN OF LANGUAGE VARIABLES

Dont edit                     ||      Edit                             */

$_lang_file_translator        		= 'Anders Hallkvist - <a href="http://flog.folkbitar.se/" target="_blank">flog.folkbitar.se</a>';
$_lang_file_email             		= 'anders [at] folkbitar.se';
$_lang_file_rev               		= '1.7';

// IMAGE NAVIGATION
$lang_previous                		= "F&ouml;reg&aring;ende";
$lang_next                    		= "N&auml;sta";
$lang_no_previous             		= "Ingen bild";
$lang_no_next                 		= "Ingen bild";
$lang_latest					 	= "Sista";
$lang_first										 = "F&ouml;rsta";
$lang_browse_select_category  = "V&auml;lj kategori";
$lang_browse_all              = "Alla";
$lang_paged_archive						= "Arkiv";

// COMMENTS
$lang_message_missing_image   = "Ingen bild vald, kommentaren sparades inte.";
$lang_message_missing_comment = "Inget meddelande, kommentaren sparades inte.";
$lang_visit_homepage          = "Bes&ouml;k hemsida";
$lang_no_comments_yet         = "Inga kommentarer &auml;nnu.";
$lang_comment_thank_you       = "Tack f&ouml;r ditt bes&ouml;k och f&ouml;r att du tog dig tid att kommentera en bild!";
$lang_comment_redirect        = "Klicka f&ouml;r att g&aring; tillbaka.";
$lang_comment_redirect_error  = "Ett fel uppstod! Om du inte automatiskt slussas tilbaka till f&ouml;reg&aring;ende sida, klicka h&auml;r.";
$lang_message_moderating_comment = "Din kommentar &auml;r mottagen Den kommer att publiceras efter det att den har blivit godk&auml;nd av administrat&ouml;ren.";
$lang_comment_page_title      = "Kommentera";
$lang_comment_popup           = "Kommentarer";
$lang_message_banned_comment  = "Din kommentar sparades inte! Den inneh&aring;ller ett eller flera bannade ord/epostadresser/ipnummer.";
$lang_comment_popup_disabled  = "Kommentarer f&ouml;r denna bilden &auml;r avst&auml;ngd";
$lang_comment_plural						 = "Kommentarer";
$lang_comment_single						 = "Kommentar";
$lang_tags                    = "Taggar:<br/>";
$lang_none                       = "inga";

// EXIF DATA
$lang_exposure              = "Exponering:";
$lang_aperture              = "Bl&auml;ndare:";
$lang_capture_date          = "Tagen:";
$lang_focal                 = "Br&auml;nnvidd:";
$lang_camera_maker          = "Kameram&auml;rke:";
$lang_camera_model          = "Kameramodell:";
$lang_flash_fired           = "Blixt: Avfyrad";
$lang_flash_not_fired       = "Blixt: Ej avfyrad";
$lang_flash_not_detected         = "Blixt: Ej avfyrad";
$lang_iso      = "ISO:";

// Category
$lang_category_singular    = "Kategori:";
$lang_category_plural      = "Kategorier:";

// Month and Day
$lang_monday              = "m&aring;ndag";
$lang_tuesday             = "tisdag";
$lang_wednesday           = "onsdag";
$lang_thursday            = "torsdag";
$lang_friday              = "fredag";
$lang_saturday            = "l&ouml;rdag";
$lang_sunday              = "s&ouml;ndag";

$lang_january             = "januari";
$lang_february            = "februari";
$lang_march               = "mars";
$lang_april               = "april";
$lang_may                 = "maj";
$lang_june                = "juni";
$lang_july                = "juli";
$lang_august              = "augusti";
$lang_september           = "september";
$lang_october             = "oktober";
$lang_november            = "november";
$lang_december            = "december";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";


// Email Notification

$lang_email_notification_subject = "Ny kommentar";
$lang_email_notification_pt1 = "
	  Hej,<br>
      en ny kommentar har postats i din fotoblogg.<br><br>
	  ";
$lang_email_notification_pt2 = "
      <br>
      Kommentaren &auml;r: <br>
      ----------------------------------------------------------------------<br>
	  ";
$lang_email_notification_pt3 = "av";
$lang_email_notification_pt4 = "
            ----------------------------------------------------------------------    <br>
      Eposten &auml;r skickad av pixelpost<br>
";
$lang_email_notificationplain_pt1 = "
	  Hej,
      en ny kommentar har postats i din fotoblogg.";
$lang_email_notificationplain_pt2 = "
      Kommentaren &auml;r:
      ----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "av";
$lang_email_notificationplain_pt4 = "
      ----------------------------------------------------------------------
      Eposten &auml;r skickad av pixelpost
";
// Error Message
$lang_nothing_to_show             = "Kommer snart! Ingenting finns att se h&auml;r &auml;nnu, eller s&aring; postas bilderna automatiskt senare!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Commentflood-skydd &auml;r aktiverat. Du m&aring;ste v&auml;nta <TIME_TO_WAIT> innan du kan posta en ny kommentar.";


// RSS & ATOM Feed
$lang_comment_feed_title        = "Senaste kommentarer till";
$lang_comment_feed_image_title  = "Ny kommentar till";
?>