<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-simplified_chinese.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'jdleungs.com';
$_lang_file_email             = 'jdleungs@gmail.com';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                    = "&laquo;";
$lang_next                        = "&raquo;";
$lang_no_previous                 = "没有上一张图片";
$lang_no_next                     = "没有下一张图片";
$lang_latest									 = "最后一张";
$lang_first										 = "第一张";
$lang_browse_select_category      = "选择类别";
$lang_browse_all                  = "全部";
$lang_permalink                   = "永久连接";
$lang_paged_archive						= "存档";

// COMMENTS
$lang_message_missing_image      = "没有选取图片。评论没有保存。";
$lang_message_missing_comment    = "没有输入信息。评论没有保存。";
$lang_message_missing_name       = "没有输入名字。评论没有保存。";
$lang_message_moderating_comment = "已经收到您的评论！管理员检视后就会发布。";
$lang_visit_homepage             = "浏览首页";
$lang_no_comments_yet            = "暂时还没有评论。";
$lang_comment_thank_you          = "感谢您的访问以及花时间评论相片。现在将会返回刚才的页面。";
$lang_comment_redirect           = "如果浏览器没有自动返回，请点击返回。";
$lang_comment_redirect_error     = "评论发送错误！如果浏览器没有自动返回，请点击返回。";
$lang_comment_page_title         = "评论";
$lang_comment_popup              = "评论";
$lang_comment_plural						 = "评论";
$lang_comment_single						 = "评论";


// EXIF DATA
$lang_exposure                   = "快门:";
$lang_aperture                   = "光圈:";
$lang_capture_date               = "拍摄时间:";
$lang_focal                      = "焦距:";
$lang_camera_maker               = "相机生产商:";
$lang_camera_model               = "相机型号:";
$lang_flash_fired                = "闪光:有";
$lang_flash_not_fired            = "闪光:没有";
$lang_flash_not_detected         = "闪光:没有检测到";
$lang_iso                        = "感光度:";

// Category
$lang_category_singular          = "类别:";
$lang_category_plural            = "类别:";

// Month and Day
$lang_monday                     = "一";
$lang_tuesday                    = "二";
$lang_wednesday                  = "三";
$lang_thursday                   = "四";
$lang_friday                     = "五";
$lang_saturday                   = "六";
$lang_sunday                     = "日";

$lang_january                   = "一月";
$lang_february                  = "二月";
$lang_march                     = "三月";
$lang_april                     = "四月";
$lang_may                       = "五月";
$lang_june                      = "六月";
$lang_july                      = "七月";
$lang_august                    = "八月";
$lang_september                 = "九月";
$lang_october                   = "十月";
$lang_november                  = "十一月";
$lang_december                  = "十二月";

// newly added
$lang_message_banned_comment     = "您的评论没有保存！因里面含有禁止使用的语句或电子邮件。";
$lang_comment_popup_disabled     = "这幅图已被禁止评论";
$lang_tags                       = "标签:<br/>";
$lang_none                       = "没有";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="简体中文";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";

// Email Notification

$lang_email_notification_subject = "新评论";
$lang_email_notification_pt1 = "
	  您好,<br>
      网站有新的评论。<br><br>
	  ";
$lang_email_notification_pt2 = "
      <br>
      以下是评论：<br>
      ----------------------------------------------------------------------<br>
	  ";
$lang_email_notification_pt3 = "来自";
$lang_email_notification_pt4 = "
            ----------------------------------------------------------------------    <br>
      电子邮件发自pixelpost<br>
";
$lang_email_notificationplain_pt1 = "
	  您好,
      网站有新的评论。";
$lang_email_notificationplain_pt2 = "
      以下是评论：
      ----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "来自";
$lang_email_notificationplain_pt4 = "
      ----------------------------------------------------------------------
      电子邮件发自pixelpost
";
// Error message
$lang_nothing_to_show             = "即将开放！没有任何图片或这些图片暂时没开放显示！";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "大量评论保护已启动。您要等待 <TIME_TO_WAIT>，才能提交下一个评论。";


// RSS & ATOM Feed
$lang_comment_feed_title        = "新评论对于";
$lang_comment_feed_image_title  = "新评论对于";
?>