<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-italian.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________

BEGIN OF LANGUAGE VARIABLES:

Dont edit                     ||       Edit                                    */

$_lang_file_translator        = 'Cristiano Gazzi (kroom) - <a href="http://www.roomk.it/" target="_blank">www.roomk.it</a>';
$_lang_file_email             = 'unkown';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                = "Precedente";
$lang_next                    = "Successiva";
$lang_no_previous             = "Nessuna Immagine Precedente";
$lang_no_next                 = "Nessuna Immagine Successiva";
$lang_latest									 = "Ultima";
$lang_first										 = "Prima";
$lang_browse_select_category  = "Seleziona Categoria";
$lang_browse_all              = "Tutte";
$lang_permalink               = "Permalink";
$lang_paged_archive						= "Archivio";

// COMMENTS
$lang_message_missing_image   = "Nessuna immagine selezionata. Il commento non &egrave; stato salvato.";
$lang_message_missing_comment = "Nessun messaggio inserito. Il commento non &egrave; stato salvato.";
$lang_visit_homepage          = "Visita la Homepage";
$lang_no_comments_yet         = "Nessun commento, per ora.";
$lang_comment_thank_you       = "Grazie per la visita e per il tempo dedicato a commentare l'immagine.\nSarete reindirizzati in 5 secondi.";
$lang_comment_redirect        = "Fare click qui per tornare indietro.";
$lang_comment_redirect_error  = "Errore nell&prime;invio del commento! Fare click per tornare indietro, se il reindirizzamento automatico non funziona.";
$lang_comment_page_title      = "Commento";
$lang_comment_popup           = "Commenti";
$lang_message_banned_comment  = "Il vostro commento non &egrave; stato accettato! Contiene una o pi&ugrave; parole/email/ip vietati.";
$lang_comment_popup_disabled  = "Commenting on this picture has been disabled";
$lang_comment_plural						 = "Comments";
$lang_comment_single						 = "Comment";
$lang_tags                    = "Tags:<br/>";
$lang_none                       = "nessuno";

// EXIF DATA
$lang_exposure              = "Esposizione:";
$lang_aperture              = "Apertura:";
$lang_capture_date          = "Data Scatto:";
$lang_focal                 = "Focale:";
$lang_camera_maker          = "Marca:";
$lang_camera_model          = "Modello:";
$lang_flash_fired           = "Flash: Utilizzato";
$lang_flash_not_fired       = "Flash: Non Utilizzato";
$lang_flash_not_detected         = "Flash: Non Rilevato";
$lang_iso                   = "ISO:";

// Category
$lang_category_singular    = "Categoria:";
$lang_category_plural      = "Categorie:";

// Month and Day

$lang_monday              = "Luned&igrave;";
$lang_tuesday             = "Marted&igrave;";
$lang_wednesday           = "Mercoled&igrave;";
$lang_thursday            = "Gioved&igrave;";
$lang_friday              = "Venerd&igrave;";
$lang_saturday            = "Sabato";
$lang_sunday              = "Domenica";

$lang_january             = "Gennaio";
$lang_february            = "Febbraio";
$lang_march               = "Marzo";
$lang_april               = "Aprile";
$lang_may                 = "Maggio";
$lang_june                = "Giugno";
$lang_july                = "Luglio";
$lang_august              = "Agosto";
$lang_september           = "Settembre";
$lang_october             = "Ottobre";
$lang_november            = "Novembre";
$lang_december            = "Dicembre";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch				="Nederlands";
$lang_alt_lang_english				="English";
$lang_alt_lang_french				="Fran&ccedil;ais";
$lang_alt_lang_german				="Deutsch";
$lang_alt_lang_italian				="Italiano";
$lang_alt_lang_norwegian			="Norsk";
$lang_alt_lang_persian				="Farsi";
$lang_alt_lang_polish				="Polski";
$lang_alt_lang_portuguese			="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish				="Espa&ntilde;ol";
$lang_alt_lang_swedish				="Svenska";
$lang_alt_lang_japanese				="Japanese";
$lang_alt_lang_danish				="Dansk";
$lang_alt_lang_romanian 			="Romana";
$lang_alt_lang_hungarian			="Magyar";


// Email Notification

$lang_email_notification_subject = "Nuovo Commento";
$lang_email_notification_pt1 = "Ciao,<br />Il tuo photoblog ha ricevuto un nuovo commento.<br /><br />";
$lang_email_notification_pt2 = "<br />Il commento &egrave;: <br />\n----------------------------------------------------------------------<br />";
$lang_email_notification_pt3 = "da";
$lang_email_notification_pt4 = "----------------------------------------------------------------------    <br />
                               Email inviata da Pixelpost<br />";
$lang_email_notificationplain_pt1 = "Ciao,\nIl tuo photoblog ha ricevuto un nuovo commento.";
$lang_email_notificationplain_pt2 = "\n\nIl commento &egrave;:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "da";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail inviata da Pixelpost";

// Error Message
$lang_nothing_to_show             = "Presto online! Niente da mostrare. Non ci sono immagini, oppure sono state impostate per visualizzazione futura!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "La protezione contro il comment flood &egrave; attiva. Devi attendere <TIME_TO_WAIT> prima di poter pubblicare un altro commento.";


// RSS & ATOM Feed
$lang_comment_feed_title        = "Commenti pi&ugrave; recenti per";
$lang_comment_feed_image_title  = "Nuovo commento per";

// End of language file
?>