<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-spanish.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'el Trauko - <a href="http://trauko.org/" target="_blank">http://trauko.org</a>';
$_lang_file_email             = 'cesar@trauko.org';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                    = "Anterior";
$lang_next                        = "Siguiente";
$lang_no_previous                 = "Primera imagen";
$lang_no_next                     = "&Uacute;ltima imagen";
$lang_latest					  = "&Uacute;ltima";
$lang_first		  				  = "Primera";
$lang_browse_select_category      = "Seleccione una Categor&iacute;a";
$lang_browse_all                  = "Todas";
$lang_permalink                   = "Permalink";
$lang_paged_archive				  = "Archivo";

// COMMENTS
$lang_message_missing_image      = "No se seleccion&oacute; nada. El comentario no se guard&oacute;.";
$lang_message_missing_comment    = "Falta un mensaje. El comentario no se guard&oacute;.";
$lang_message_missing_name       = "Falta el nombre. El comentario no se guard&oacute;.";
$lang_message_moderating_comment = "&iexcl;Su comentario fue recibido!. Ser&aacute; publicado despu&eacute;s de ser autorizado por el administrador.";
$lang_visit_homepage             = "Visite la p&aacute;gina Web";
$lang_no_comments_yet            = "No hay comentarios a&uacute;n.";
$lang_comment_thank_you          = "Gracias por la visita y por su comentario. Sera redirigido ahora.";
$lang_comment_redirect           = "Por favor pincha ac&aacute; para regresar, si la redirecci&oacute;n no funciona";
$lang_comment_redirect_error     = "&iexcl;Error al subir el comentario! Por favor pincha ac&aacute; para ser redirigido";
$lang_comment_page_title         = "Comentario";
$lang_comment_popup              = "Comentarios";
$lang_comment_popup_disabled     = "Los comentarios en &eacute;sta imagen est&aacute;n desactivados";
$lang_comment_plural			 = "Comentarios";
$lang_comment_single			 = "Comentario";

// EXIF DATA
$lang_exposure                   = "Exposici&oacute;n:";
$lang_aperture                   = "Aperture:";
$lang_capture_date               = "Fecha:";
$lang_focal                      = "Distancia focal:";
$lang_camera_maker               = "Fabricante:";
$lang_camera_model               = "Modelo:";
$lang_flash_fired                = "Flash: disparado";
$lang_flash_not_fired            = "Flash: no disparado";
$lang_flash_not_detected         = "Flash: no detectado";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "Categor&iacute;a:";
$lang_category_plural            = "Categor&iacute;as:";

// Month and Day
$lang_monday                     = "Lunes";
$lang_tuesday                    = "Martes";
$lang_wednesday                  = "Mi&eacute;rcoles";
$lang_thursday                   = "Jueves";
$lang_friday                     = "Viernes";
$lang_saturday                   = "S&aacute;bado";
$lang_sunday                     = "Domingo";

$lang_january                   = "Enero";
$lang_february                  = "Febrero";
$lang_march                     = "Marzo";
$lang_april                     = "Abril";
$lang_may                       = "Mayo";
$lang_june                      = "Junio";
$lang_july                      = "Julio";
$lang_august                    = "Agosto";
$lang_september                 = "Septiembre";
$lang_october                   = "Octubre";
$lang_november                  = "Noviembre";
$lang_december                  = "Diciembre";

// newly added
$lang_message_banned_comment     = "&iexcl;Su comentario no se guard&oacute;! Contiene una o m&aacute;s palabras/eMail/IPs prohibidas.";
$lang_tags                       = "Etiquetas:<br/>";
$lang_none                       = "ninguno";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch				="Nederlands";
$lang_alt_lang_english				="English";
$lang_alt_lang_french				="Fran&ccedil;ais";
$lang_alt_lang_german				="Deutsch";
$lang_alt_lang_italian				="Italiano";
$lang_alt_lang_norwegian			="Norsk";
$lang_alt_lang_persian				="Farsi";
$lang_alt_lang_polish				="Polski";
$lang_alt_lang_portuguese			="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish				="Espa&ntilde;ol";
$lang_alt_lang_swedish				="Svenska";
$lang_alt_lang_japanese				="Japanese";
$lang_alt_lang_danish				="Dansk";
$lang_alt_lang_romanian 			="Romana";
$lang_alt_lang_hungarian			="Magyar";


// Email Notification

$lang_email_notification_subject = "Nuevo comentario";
$lang_email_notification_pt1 = "Hola,<br>Un nuevo comentario se hizo en tu fotoblog.<br><br>";
$lang_email_notification_pt2 = "<br>El comentario es: <br> ----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "de";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\neMail enviado por PixelPost<br>";
$lang_email_notificationplain_pt1 = "Hola,\nUn nuevo comentario se hizo en tu fotoblog.";
$lang_email_notificationplain_pt2 = "\n\nEl comentario es:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "de";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail sent by Pixelpost";

// Error message
$lang_nothing_to_show             = "Nada que mostrar a&uacute;n. &iexcl;Pronto este sitio estar&aacute; activo!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "La proteci&oacute;n de comentarios esta activada. Espera <TIME_TO_WAIT> antes de ingresar otro comentario.";


// RSS & ATOM Feeds
$lang_comment_feed_title        = "Comentarios nuevos en";
$lang_comment_feed_image_title  = "Nuevo comentario en";
?>