<?php

/*

Pixelpost version 1.5

SVN file version:
$Id$

Language file: english/default


Version 1.5:
Development Team:
Ramin Mehran, Connie Mueller-Goedecke, Will Duncan, Joseph Spurling, GeoS
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew@Pixelpost.org
Copyright  2006 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki:     http://wiki.pixelpost.org/ 
Pixelpost forum: 	http://forum.pixelpost.org


License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                      ||  Edit                                                        */

// IMAGE NAVIGATION
$lang_nothing_to_show             = "Coming Soon! Nothing has been posted yet.";

$lang_previous                    = "Previous";
$lang_next                        = "Next";
$lang_no_previous                 = "No Previous Image";
$lang_no_next                     = "No Next Image";
$lang_browse_select_category      = "Select Category";
$lang_browse_all                  = "All";
$lang_permalink                   = "Permalink";

// COMMENTS
$lang_message_missing_image      = "No image selected. Comment was not saved.";
$lang_message_missing_comment    = "No message input. Comment was not saved.";
$lang_message_missing_name       = "No name input. Comment was not saved.";
$lang_message_moderating_comment = "Your comment is received! It will become public after authorizing by photoblog admin.";
$lang_visit_homepage             = "Visit Homepage";
$lang_no_comments_yet            = "No Comments Yet.";
$lang_comment_thank_you          = "Thank you for visiting and taking the time to comment on a picture. You will be redirected now.";
$lang_comment_redirect           = "Please click to be transferred back, if redirection doesn't work";
$lang_comment_redirect_error     = "Comment submission error! Please click to be transferred back, if redirection doesn't work";
$lang_comment_page_title         = "Comment";
$lang_comment_popup              = "Comments";

// EXIF DATA
$lang_exposure                   = "Exposure:";
$lang_aperture                   = "Aperture:";
$lang_capture_date               = "Capture Date:";
$lang_focal                      = "Focal:";
$lang_camera_maker               = "Camera Maker:";
$lang_camera_model               = "Camera Model:";
$lang_flash_fired                = "Flash: Fired";
$lang_flash_not_fired            = "Flash: Not Fired";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "Category:";
$lang_category_plural            = "Categories:";

// Month and Day
$lang_monday                     = "Monday";
$lang_tuesday                    = "Tuesday";
$lang_wednesday                  = "Wednesday";
$lang_thursday                   = "Thursday";
$lang_friday                     = "Friday";
$lang_saturday                   = "Saturday";
$lang_sunday                     = "Sunday";

$lang_january                   = "January";
$lang_february                  = "February";
$lang_march                     = "March";
$lang_april                     = "April";
$lang_may                       = "May";
$lang_june                      = "June";
$lang_july                      = "July";
$lang_august                    = "August";
$lang_september                 = "September";
$lang_october                   = "October";
$lang_november                  = "November";
$lang_december                  = "December";

// newly added
$lang_message_banned_comment     = "Your comment hasn't been saved! It contains one or more banned words/email/IPs.";

// Email Notification

$lang_email_notification_subject = "New Comment";
$lang_email_notification_pt1 = "Hello,<br>A new comment has been made at your photoblog.<br><br>";	  
$lang_email_notification_pt2 = "<br>The comment is: <br> ----------------------------------------------------------------------<br>";	  
$lang_email_notification_pt3 = "by";  
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\nEmail sent by Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Hello,\n\A new comment has been made at your photoblog.";	  
$lang_email_notificationplain_pt2 = "\n\nThe comment is:\n\n----------------------------------------------------------------------";	  
$lang_email_notificationplain_pt3 = "by";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail sent by Pixelpost";

// Error message
$lang_nothing_to_show             = "Coming Soon! Nothing to show. No image to show here!";
?>