<?php
/*

lang-danish.php
===============
Pixelpost version 1.7

SVN file version:
$Id$

Language file: Danish (DK)
Author:  Andreas M&oslash;gelmose
Contact: andreas@xerxes.dk
WWW: http://fotoblog.xerxes.dk

Version 1.5:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling, Piotr "GeoS" Galas
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright  2006 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki:     http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org


License: http://www.gnu.org/copyleft/gpl.html

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-

Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'Andreas M&oslash;gelmose';
$_lang_file_email             = 'andreas@xerxes.dk';
$_lang_file_rev               = '1.6';

// IMAGE NAVIGATION
$lang_previous                    = "Forrige";
$lang_next                        = "N&aelig;ste";
$lang_no_previous                 = "Intet foreg&aring;ende billede";
$lang_no_next                     = "Ikke flere billeder";
$lang_latest										  = "Seneste";
$lang_first		  								  = "F&oslash;rste";
$lang_browse_select_category      = "V&aelig;lg kategori";
$lang_browse_all                  = "Alle";
$lang_permalink                   = "Permalink";
$lang_paged_archive								= "Arkiv";

// COMMENTS
$lang_message_missing_image      = "Intet billede valgt. Kommentaren blev ikke gemt.";
$lang_message_missing_comment    = "Ingen besked angivet. Kommentaren blev ikke gemt.";
$lang_message_missing_name       = "Intet navn angivet. Kommentaren blev ikke gemt.";
$lang_message_moderating_comment = "Din kommentar er modtaget! Den bliver offentliggjort efter godkendelse af administratoren.";
$lang_visit_homepage             = "Bes&oslash;g hjemmeside";
$lang_no_comments_yet            = "Endnu ingen kommentarer.";
$lang_comment_thank_you          = "Tak for bes&oslash;get og for at have taget dig tid til at kommentere. Du bliver videresendt nu.";
$lang_comment_redirect           = "Klik for at komme tilbage hvis viderestillingen ikke fungerer";
$lang_comment_redirect_error     = "Fejl i indsendelsen af kommentar!Comment submission error! Klik for at komme tilbage hvis viderestillingen ikke fungerer";
$lang_comment_page_title         = "Kommentér";
$lang_comment_popup              = "Kommentarer";
$lang_comment_popup_disabled     = "Kommentarer er sl&aring;et fra p&aring; dette billede";
$lang_comment_plural						 = "Kommentarer";
$lang_comment_single						 = "Kommentér";


// EXIF DATA
$lang_exposure              	= "Lukkertid:";
$lang_aperture              	= "Bl&aelig;nde:";
$lang_capture_date          	= "Dato:";
$lang_focal                 	= "Fokus:";
$lang_camera_maker          	= "Kameraproducent:";
$lang_camera_model          	= "Kameramodel:";
$lang_flash_fired           	= "Med flash";
$lang_flash_not_fired       	= "Uden flash";
$lang_flash_not_detected         = "Flash: Not Detected";
$lang_iso		    			= "ISO:";

// Category
$lang_category_singular	  		= "Kategori:";
$lang_category_plural      		= "Kategorier:";

// Month and Day
$lang_monday              		= "mandag";
$lang_tuesday             		= "tirsdag";
$lang_wednesday           		= "onsdag";
$lang_thursday            		= "torsdag";
$lang_friday              		= "fredag";
$lang_saturday            		= "l&oslash;rdag";
$lang_sunday              		= "s&oslash;ndag";

$lang_january             		= "januar";
$lang_february            		= "februar";
$lang_march               		= "marts";
$lang_april               		= "april";
$lang_may                 		= "maj";
$lang_june               		= "juni";
$lang_july             			= "juli";
$lang_august           		   	= "august";
$lang_september           		= "september";
$lang_october             		= "oktober";
$lang_november            		= "november";
$lang_december            		= "december";

// newly added
$lang_message_banned_comment     = "Din kommentar er ikke blevet gemt! Den indeholder et eller flere ord/e-mails/IP'er, der ikke er tilladt.";
$lang_tags                       = "N&oslash;gleord:<br/>";

// Alternative language
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Français";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Português";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Español";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish						="Dansk";

// Email Notification

$lang_email_notification_subject = "Ny kommentar";
$lang_email_notification_pt1 = "Hej<br>En ny kommentar er blevet lagt p&aring; din fotoblog.<br><br>";
$lang_email_notification_pt2 = "<br>Kommentaren er: <br> ----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "af";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\nE-mail sendt af Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Hej\nEn ny kommentar er blevet lagt p&aring; din fotoblog.";
$lang_email_notificationplain_pt2 = "\n\nKommentaren er: \n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "af";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nE-mail sendt af Pixelpost";

// Error message
$lang_nothing_to_show             	= "Kommer snart! Der er endnu ikke postet noget her or they are set to show in future.";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Comment flood protection is enabled. You need to wait <TIME_TO_WAIT> before posting another comment.";


// RSS & ATOM Feed
$lang_comment_feed_title        = "Newest comments on";
$lang_comment_feed_image_title  = "New comment on";
?>