<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-english.php 453 2007-10-28 14:18:49Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'The Pixelpost Crew';
$_lang_file_email             = 'thecrew@pixelpost.org';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                    = "Previous";
$lang_next                        = "Next";
$lang_no_previous                 = "No Previous Image";
$lang_no_next                     = "No Next Image";
$lang_latest					  = "Last";
$lang_first		  				  = "First";
$lang_browse_select_category      = "Select Category";
$lang_browse_all                  = "All";
$lang_permalink                   = "Permalink";
$lang_paged_archive				  = "Archive";

// COMMENTS
$lang_message_missing_image      = "No image selected. Comment was not saved.";
$lang_message_missing_comment    = "No message input. Comment was not saved.";
$lang_message_missing_name       = "No name input. Comment was not saved.";
$lang_message_moderating_comment = "Your comment is received! It will become public after authorizing by photoblog admin.";
$lang_visit_homepage             = "Visit Homepage";
$lang_no_comments_yet            = "No Comments Yet.";
$lang_comment_thank_you          = "Thank you for visiting and taking the time to comment on a picture. You will be redirected now.";
$lang_comment_redirect           = "Please click to be transferred back, if redirection doesn't work";
$lang_comment_redirect_error     = "Comment submission error! Please click to be transferred back, if redirection doesn't work";
$lang_comment_page_title         = "Comment";
$lang_comment_popup              = "Comments";
$lang_comment_popup_disabled     = "Commenting on this picture has been disabled";
$lang_comment_plural			 = "Comments";
$lang_comment_single			 = "Comment";

// EXIF DATA
$lang_exposure                   = "Exposure:";
$lang_aperture                   = "Aperture:";
$lang_capture_date               = "Capture Date:";
$lang_focal                      = "Focal Length:";
$lang_camera_maker               = "Camera Maker:";
$lang_camera_model               = "Camera Model:";
$lang_flash_fired                = "Flash: Fired";
$lang_flash_not_fired            = "Flash: Not Fired";
$lang_flash_not_detected         = "Flash: Not Detected";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "Category:";
$lang_category_plural            = "Categories:";

// Month and Day
$lang_monday                     = "Monday";
$lang_tuesday                    = "Tuesday";
$lang_wednesday                  = "Wednesday";
$lang_thursday                   = "Thursday";
$lang_friday                     = "Friday";
$lang_saturday                   = "Saturday";
$lang_sunday                     = "Sunday";

$lang_january                   = "January";
$lang_february                  = "February";
$lang_march                     = "March";
$lang_april                     = "April";
$lang_may                       = "May";
$lang_june                      = "June";
$lang_july                      = "July";
$lang_august                    = "August";
$lang_september                 = "September";
$lang_october                   = "October";
$lang_november                  = "November";
$lang_december                  = "December";

// newly added
$lang_message_banned_comment     = "Your comment hasn't been saved! It contains one or more banned words/email/IPs.";
$lang_tags                       = "Tags:<br/>";
$lang_none                       = "none";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch				="Nederlands";
$lang_alt_lang_english				="English";
$lang_alt_lang_french				="Fran&ccedil;ais";
$lang_alt_lang_german				="Deutsch";
$lang_alt_lang_italian				="Italiano";
$lang_alt_lang_norwegian			="Norsk";
$lang_alt_lang_persian				="Farsi";
$lang_alt_lang_polish				="Polski";
$lang_alt_lang_portuguese			="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish				="Espa&ntilde;ol";
$lang_alt_lang_swedish				="Svenska";
$lang_alt_lang_japanese				="Japanese";
$lang_alt_lang_danish				="Dansk";
$lang_alt_lang_romanian 			="Romana";
$lang_alt_lang_hungarian			="Magyar";

// Email Notification

$lang_email_notification_subject = "New Comment";
$lang_email_notification_pt1 = "Hello,<br>A new comment has been made at your photoblog.<br><br>";
$lang_email_notification_pt2 = "<br>The comment is: <br> ----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "by";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\nEmail sent by Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Hello,\nA new comment has been made at your photoblog.";
$lang_email_notificationplain_pt2 = "\n\nThe comment is:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "by";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail sent by Pixelpost";

// Error message
$lang_nothing_to_show             = "Coming Soon! Nothing to show. No image to show here or they are set to show in future!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Comment flood protection is enabled. You need to wait <TIME_TO_WAIT> before posting another comment.";


// RSS & ATOM Feeds
$lang_comment_feed_title        = "Newest comments on";
$lang_comment_feed_image_title  = "New comment on";
?>