<?php
/*

Pixelpost version 1.7

SVN file version:
$Id: lang-norwegian.php 456 2007-10-30 18:41:12Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                   ||  Edit                                                        */

$_lang_file_translator        = 'John Christian Olsen - <a href="http://jcolsen.com/" target="_blank">jcolsen.com</a>';
$_lang_file_email             = 'info@jcolsen.com';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                   = "Forrige";
$lang_next                      = "Neste";
$lang_no_previous               = "Ingen tidligere bilder";
$lang_no_next                   = "Ingen flere bilder";
$lang_latest									 = "Siste";
$lang_first										 = "F&oslash;rste";
$lang_browse_select_category    = "Velg kategori";
$lang_browse_all                = "Alle";
$lang_paged_archive							= "Arkiv";

// COMMENTS
$lang_message_missing_image     = "Inget bilde var valgt, kommentaren ble ikke lagret.";
$lang_message_missing_comment   = "Ingen beskjed gitt. Kommentaren ble ikke lagret.";
$lang_visit_homepage            = "Bes&oslash;k hjemmeside";
$lang_no_comments_yet           = "Ingen kommentarer forel&oslash;pig.";
$lang_comment_thank_you         = "Takk for kommentaren.";
$lang_comment_redirect          = "Klikk for &aring; g&aring; tilbake.";
$lang_message_moderating_comment = "Din kommentar er mottatt! Den vil bli synlig etter godkjennelse fra fotobloggens administrator.";
$lang_comment_redirect_error    = "Kommentar ble ikke postet p&aring; grunn av en feil! Vennligst klikk for &aring; komme tilbake, hvis videref&oslash;relse ikke virker";
$lang_comment_page_title        = "Kommentar";
$lang_comment_popup             = "Kommentarer";
$lang_message_banned_comment    = "Din kommentar er ikke lagret! Det inneholder ett eller flere ikke godkjente ord/e-post(er)/ip adresse(r).";
$lang_comment_popup_disabled    = "Kommentarer p&aring; dette bildet er deaktivert";
$lang_comment_plural						= "Kommentarer";
$lang_comment_single						= "Kommentar";
$lang_tags                      = "Tags:<br/>";
$lang_none                       = "ingen";

// EXIF DATA
$lang_exposure              = "Lukkertid:";
$lang_aperture              = "Blender:";
$lang_capture_date          = "Dato:";
$lang_focal                 = "Fokus:";
$lang_camera_maker          = "Kameraprodusent:";
$lang_camera_model          = "Kameramodell:";
$lang_flash_fired           = "Blitz: Ja";
$lang_flash_not_fired       = "Blitz: Nei";
$lang_flash_not_detected         = "Flash: Ikke oppdaget";
$lang_iso                   = "ISO:";

// Category
$lang_category_singular	   = "Kategori:";
$lang_category_plural      = "Kategorier:";

// Month and Day
$lang_monday              = "mandag";
$lang_tuesday             = "tirsdag";
$lang_wednesday           = "onsdag";
$lang_thursday            = "torsdag";
$lang_friday              = "fredag";
$lang_saturday            = "l&oslash;rdag";
$lang_sunday              = "s&oslash;ndag";

$lang_january             = "januar";
$lang_february            = "februar";
$lang_march               = "mars";
$lang_april               = "april";
$lang_may                 = "mai";
$lang_june                = "juni";
$lang_july                = "juli";
$lang_august              = "august";
$lang_september           = "september";
$lang_october             = "oktober";
$lang_november            = "november";
$lang_december            = "desember";

// Alternative language
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Français";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Português";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Español";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish						="Dansk";

// Email Notification

$lang_email_notification_subject = "Ny kommentar";
$lang_email_notification_pt1 = "Hei,<br>En ny kommentar er blitt postet p&aring; din fotoblog.<br><br>";
$lang_email_notification_pt2 = "<br>Kommentaren er: <br>----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "av";
$lang_email_notification_pt4 = "\n\n----------------------------------------------------------------------    <br>\n\nE-post sent av Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Hei,\n\nEn ny kommentar er blitt postet p&aring; din fotoblog.";
	$lang_email_notificationplain_pt2 = "\n\nKommentaren er:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "av";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nE-post sent av Pixelpost";
// Error Message
$lang_nothing_to_show             = "Kommer snart! Ingenting &aring; vise for &oslash;yeblikket. Enten er det ingen bilder i bloggen, eller s&aring; er dem satt til &aring; vise i senere fremtid!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Multikommentar beskyttelse er p&aring;sl&aring;tt. Du m&aring; vente <TIME_TO_WAIT> f&oslash;r du kan poste en ny kommentar.";



// RSS & ATOM Feed
$lang_comment_feed_title        = "Nyeste kommentar p&aring;";
$lang_comment_feed_image_title  = "Ny kommentar p&aring;";
?>