<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-dutch.php 434 2007-10-19 16:59:01Z schonhose $

Pixelpost version 1.7

SVN file version:
$Id: lang-dutch.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
BEGIN OF LANGUAGE VARIABLES:

Dont edit                     ||       Edit                                    */

$_lang_file_translator        = 'Schonhose - <a href="http://foto.schonhose.nl/" target="_blank">foto.schonhose.nl</a>';
$_lang_file_email             = 'schonhose@pixelpost.org';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_nothing_to_show          = "Nog niet gereed! Hier zijn nog geen afbeeldingen te bekijken!";

$lang_previous                 = "Vorige";
$lang_next                     = "Volgende";
$lang_no_previous              = "Geen vorige afbeelding";
$lang_no_next                  = "Geen volgende afbeelding";
$lang_latest									 = "Laatste";
$lang_first										 = "Eerste";
$lang_browse_select_category   = "Kies categorie";
$lang_browse_all               = "Alles";
$lang_permalink                = "Permalink";
$lang_paged_archive						 = "Archief";

// COMMENTS
$lang_message_missing_image   = "Geen afbeelding geselecteerd. Uw reactie werd niet bewaard.";
$lang_message_missing_comment = "Geen commentaar ingevoerd. Uw reactie werd niet bewaard.";
$lang_visit_homepage          = "Bezoek de voorpagina";
$lang_no_comments_yet         = "Nog geen reacties.";
$lang_comment_thank_you       = "Bedankt voor je bezoek en om de tijd te nemen om een reactie te geven op een afbeelding.\nDeze pagina wordt automatisch ververst na 5 seconden";
$lang_comment_redirect        = "Klik hier om terug te keren.";
$lang_comment_redirect_error  = "Fout tijdens het opslaan van de reactie! Klik om terug te keren wanneer u niet automatisch teruggestuurd wordt.";
$lang_comment_page_title      = "Reactie";
$lang_comment_popup           = "Reacties";
$lang_message_banned_comment  = "Uw reactie kan niet bewaard worden! Het bevat &eacute;&eacute;n of meerdere verboden woorden/email/ips.";
$lang_comment_popup_disabled  = "Reacties geven op deze afbeelding is uitgeschakeld.";
$lang_comment_plural				  = "Reacties";
$lang_comment_single					= "Reactie";
$lang_tags                    = "Label:<br/>";
$lang_none                       = "none";

// EXIF DATA
$lang_exposure              = "Belichting:";
$lang_aperture              = "Diafragma:";
$lang_capture_date          = "Opnamedatum:";
$lang_focal                 = "Brandpuntsafstand:";
$lang_camera_maker          = "Camerafabrikant:";
$lang_camera_model          = "Cameramodel:";
$lang_flash_fired           = "Flitser: Aan:";
$lang_flash_not_fired       = "Flitser: Uit";
$lang_flash_not_detected    = "Flitser: Niet Gedetecteerd";
$lang_iso                   = "ISO:";

// Category
$lang_category_singular      = "Categorie:";
$lang_category_plural        = "Categorie&euml;n:";

// Month and Day
$lang_monday              = "maandag";
$lang_tuesday             = "dinsdag";
$lang_wednesday           = "woensdag";
$lang_thursday            = "donderdag";
$lang_friday              = "vrijdag";
$lang_saturday            = "zaterdag";
$lang_sunday              = "zondag";

$lang_january             = "januari";
$lang_february            = "februari";
$lang_march               = "maart";
$lang_april               = "april";
$lang_may                 = "mei";
$lang_june                = "juni";
$lang_july                = "juli";
$lang_august              = "augustus";
$lang_september           = "september";
$lang_october             = "oktober";
$lang_november            = "november";
$lang_december            = "december";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";

// Email Notification

$lang_email_notification_subject = "Nieuwe Reactie";
$lang_email_notification_pt1 = "
	  Hallo,<br>
      Er is een nieuwe reactie geplaatst op uw photoblog.<br><br>
	  ";
$lang_email_notification_pt2 = "
      <br>
      De inhoud van de reactie is: <br>
      ----------------------------------------------------------------------<br>
	  ";
$lang_email_notification_pt3 = "door";
$lang_email_notification_pt4 = "
            ----------------------------------------------------------------------    <br>
      Email verstuurd door pixelpost<br>
";
$lang_email_notificationplain_pt1 = "
	  Hallo,<br>
      Er is een nieuwe reactie geplaatst op uw photoblog.";
$lang_email_notificationplain_pt2 = "
      De inhoud van de reactie is:
      ----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "door";
$lang_email_notificationplain_pt4 = "
      ----------------------------------------------------------------------
      Email verstuurd door pixelpost
";

// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "U moet nog <TIME_TO_WAIT> wachten voordat u een nieuwe reactie kunt plaatsen.";

// RSS & ATOM Feed
$lang_comment_feed_title        = "Laatste reacties op";
$lang_comment_feed_image_title  = "Laatste reactie op";
?>