<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-romanian.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________
*/

/* Dont edit                      ||  Edit                                                        */

$_lang_file_translator        = 'Alex Mielus';
$_lang_file_email             = 'alex@mielus.ro';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                    = "Fotografii mai vechi";
$lang_next                        = "Fotografii mai noi";
$lang_no_previous                 = "Nu exista fotografii mai vechi";
$lang_no_next                     = "Nu exista fotografii mai noi";
$lang_latest					  = "Ultima fotografie";
$lang_first		  				  = "Prima fotografie";
$lang_browse_select_category      = "Selecteaza categoria";
$lang_browse_all                  = "Toate fotografiile";
$lang_permalink                   = "Link permanent";
$lang_paged_archive				  = "Vezi arhiva";
$lang_view_on_map			  = "Vezi pe harta";

// COMMENTS
$lang_message_missing_image      = "Nu ai selectat o imagine. Comentariul nu a fost salvat.";
$lang_message_missing_comment    = "Nu ai scris nici un mesaj. Comentariul nu a fost salvat.";
$lang_message_missing_name       = "Nu ai trecut numele tau. Comentariul nu a fost salvat.";
$lang_message_moderating_comment = "Comentariul tau a fost receptionat, deci NU il posta din nou! Va aparea dupa ce George il va aproba.";
$lang_visit_homepage             = "Mergi la prima pagina a siteului";
$lang_no_comments_yet            = "Nu exista deocamdata comentarii la aceasta fotografie.";
$lang_comment_thank_you          = "Iti multumesc pentru ca m-ai vizitat si ai gasit timp pentru a posta un comentariu. Acum vei fi redirectionat.";
$lang_comment_redirect           = "In cazul in care redirectarea nu functioneaza, te rog sa apesi pentru a ajunge la pagina de unde ai plecat.";
$lang_comment_redirect_error     = "EROARE la trimiterea comentariului! In cazul in care redirectarea nu functioneaza, te rog sa apesi pentru a ajunge la pagina de unde ai plecat.";
$lang_comment_page_title         = "comentariu";
$lang_comment_popup              = "comentarii";
$lang_comment_popup_disabled     = "Comentariile la aceasta fotografie nu sunt permise.";
$lang_comment_plural			 = "comentarii";
$lang_comment_single			 = "comentariu";

// EXIF DATA
$lang_exposure                   = "Expunerea:";
$lang_aperture                   = "Diafragma:";
$lang_capture_date               = "Data:";
$lang_focal                      = "Distanta focala:";
$lang_camera_maker               = "Fabricantul camerei:";
$lang_camera_model               = "Modelul camerei:";
$lang_flash_fired                = "Blitzul a fost folosit";
$lang_flash_not_fired            = "Blitzul nu a fost folosit";
$lang_flash_not_detected         = "Blitzul nu a fost detectat";
$lang_iso                        = "ISO:";

// Category
$lang_category_singular          = "Categorie:";
$lang_category_plural            = "Categorii:";

// Month and Day
$lang_monday                     = "Luni";
$lang_tuesday                    = "Marti";
$lang_wednesday                  = "Miercuri";
$lang_thursday                   = "Joi";
$lang_friday                     = "Vineri";
$lang_saturday                   = "Sambata";
$lang_sunday                     = "Duminica";

$lang_january                   = "Ianuarie";
$lang_february                  = "Februarie";
$lang_march                     = "Martie";
$lang_april                     = "Aprilie";
$lang_may                       = "Mai";
$lang_june                      = "Iunie";
$lang_july                      = "Iulie";
$lang_august                    = "August";
$lang_september                 = "Septembrie";
$lang_october                   = "Octombrie";
$lang_november                  = "Noiembrie";
$lang_december                  = "Decembrie";

// newly added
$lang_message_banned_comment     = "Comentariul tau nu a fost salvat! Contine unul sau mai multe cuvinte / email / IPuri interzise.";
$lang_tags                       = "Taguri:<br/>";
$lang_none                       = "Nici unul (una)";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";

// Email Notification

$lang_email_notification_subject = "Un nou comentariu";
$lang_email_notification_pt1 = "Salut,<br>S-a scris un nou comentariu pe blogul foto.<br><br>";
$lang_email_notification_pt2 = "<br>Comentariu: <br> ----------------------------------------------------------------------<br>";
$lang_email_notification_pt3 = "by";
$lang_email_notification_pt4 = "----------------------------------------------------------------------<br>\n\nEmail trimis de Pixelpost<br>";
$lang_email_notificationplain_pt1 = "Salut,\nS-a scris un nou comentariu pe blogul foto.";
$lang_email_notificationplain_pt2 = "\n\nComentariu:\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3 = "by";
$lang_email_notificationplain_pt4 = "\n\n----------------------------------------------------------------------\n\nEmail trimis de Pixelpost";

// Error message
$lang_nothing_to_show             = "E pe vine! Nu e nimic de aratat momentan :) N-ai ce imagine sa vezi aici!";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood										= "Protectia contra floodului din comentarii este activa. Trebuie sa astepti <TIME_TO_WAIT> inainte de a posta un nou comentariu.";


// RSS & ATOM Feeds
$lang_comment_feed_title        = "Cele mai noi comentarii la";
$lang_comment_feed_image_title  = "Un nou comentariu la";
?>