<?php
/*
Pixelpost version 1.7

SVN file version:
$Id: lang-french.php 434 2007-10-19 16:59:01Z schonhose $

Version 1.7:
Development Team:
Ramin Mehran, Will Duncan, Joseph Spurling,
Piotr "GeoS" Galas, Dennis Mooibroek, Karin Uhlig, Jay Williams, David Kozikowski

Former members of the Development Team:
Connie Mueller-Goedecke
Version 1.1 to Version 1.3: Linus <http://www.shapestyle.se>

Contact: thecrew (at) pixelpost (dot) org
Copyright 2007 Pixelpost.org <http://www.pixelpost.org>

Pixelpost www:  	http://www.pixelpost.org/
Pixelpost wiki: 	http://wiki.pixelpost.org/
Pixelpost forum: 	http://forum.pixelpost.org
_____________________________________________________________________________
Some text are generated by the script itself and not controlled through template design.
Edit these lines of text in this file and have the script generate other wording or
in other languages.
_____________________________________________________________________________


/* Dont edit                      ||       Edit                                    */

$_lang_file_translator        = 'Philippe Durand | <a href="http:///www.photofloue.net/" target="_blank">www.photofloue.net</a>';
$_lang_file_email             = 'thecrew@pixelpost.org';
$_lang_file_rev               = '1.7';

// IMAGE NAVIGATION
$lang_previous                     = "Pr&eacute;c&eacute;dente";
$lang_next                         = "Suivante";
$lang_no_previous                  = "Pas d'image pr&eacute;c&eacute;dente";
$lang_no_next                      = "Pas d'image suivante";
$lang_latest						= "Derni&egrave;re";
$lang_first							= "Premi&egrave;re";
$lang_browse_select_category       = "S&eacute;lectionnez un mot-cl&eacute;";
$lang_browse_all                   = "Toutes";
$lang_permalink                    = "Lien permanent";
$lang_paged_archive					 = "Archive";

// COMMENTS
$lang_message_missing_image        = "Pas d'image s&eacute;lectionn&eacute;e. Commentaire non sauvegard&eacute;.";
$lang_message_missing_comment      = "Pas de message ! Commentaire non sauvegard&eacute;.";
$lang_message_missing_name         = "Pas de nom ! Commentaire non sauvegard&eacute;.";
$lang_message_moderating_comment   = "Merci de votre commentaire. Il sera publi&eacute; apres v&eacute;rification par l'administrateur du photoblog (pour &eacute;viter le spam).";
$lang_visit_homepage               = "Voir la page d'accueil";
$lang_no_comments_yet              = "Pas de commentaire.";
$lang_comment_thank_you            = "Merci de votre visite et d'avoir pris le temps de laisser un commentaire. Vous allez revenir automatiquement au photoblog.";
$lang_comment_redirect             = "Ou cliquez ici pour revenir.";
$lang_comment_redirect_error       = "Il y a eu un probl&egrave;me en envoyant votre commentaire. Cliquez ici pour revenir si cela ne se fait pas automatiquement.";
$lang_comment_page_title           = "Commentaire";
$lang_comment_popup                = "Commentaires";
$lang_comment_popup_disabled       = "Les commentaires pour cette image ne sont pas autorisŽs";
$lang_comment_plural			   = "Commentaires";
$lang_comment_single			   = "Commentaire";
$lang_message_banned_comment       = "Votre commentaire n'a pas pu &ecirc;tre enregistr&eacute; ! Il contient au moins un mot, adresse mail ou IP sur la liste des interdits.";
$lang_tags                         = "Tags :<br/>";
$lang_none                         = "aucun";

// EXIF DATA
$lang_exposure                     = "Exposition :";
$lang_aperture                     = "Ouverture :";
$lang_capture_date                 = "Date de prise de vue :";
$lang_focal                        = "Focale :";
$lang_camera_maker                 = "Marque :";
$lang_camera_model                 = "Mod&egrave;le :";
$lang_flash_fired                  = "Avec flash";
$lang_flash_not_fired              = "Sans flash";
$lang_flash_not_detected           = "Flash : inconnu";
$lang_iso                          = "ISO :";

// Category
$lang_category_singular            = "mot-cl&eacute; :";
$lang_category_plural              = "mots-cl&eacute;s :";

// Month and Day
$lang_monday 		= "lundi";
$lang_tuesday		= "mardi";
$lang_wednesday     = "mercredi";
$lang_thursday      = "jeudi";
$lang_friday        = "vendredi";
$lang_saturday      = "samedi";
$lang_sunday        = "dimanche";

$lang_january                      = "janvier";
$lang_february                     = "f&eacute;vrier";
$lang_march                        = "mars";
$lang_april                        = "avril";
$lang_may                          = "mai";
$lang_june                         = "juin";
$lang_july                         = "juillet";
$lang_august                       = "ao&ucirc;t";
$lang_september                    = "septembre";
$lang_october                      = "octobre";
$lang_november                     = "novembre";
$lang_december                     = "d&eacute;cembre";

// Alternative language (PLEASE DO NOT TRANSLATE THESE!!!)
$lang_alt_lang_dutch							="Nederlands";
$lang_alt_lang_english						="English";
$lang_alt_lang_french							="Fran&ccedil;ais";
$lang_alt_lang_german							="Deutsch";
$lang_alt_lang_italian						="Italiano";
$lang_alt_lang_norwegian					="Norsk";
$lang_alt_lang_persian						="Farsi";
$lang_alt_lang_polish							="Polski";
$lang_alt_lang_portuguese					="Portugu&egrave;s";
$lang_alt_lang_simplified_chinese	="Chinese";
$lang_alt_lang_spanish						="Espa&ntilde;ol";
$lang_alt_lang_swedish						="Svenska";
$lang_alt_lang_japanese						="Japanese";
$lang_alt_lang_danish							="Dansk";
$lang_alt_lang_romanian 					="Romana";
$lang_alt_lang_hungarian					="Magyar";



// Email Notification

$lang_email_notification_subject   = "Nouveau commentaire";
$lang_email_notification_pt1       = "Bonjour,\n<br />Un nouveau commentaire sur votre photoblog !\n<br /><br />\n";
$lang_email_notification_pt2       = "<br />Le commentaire :<br />\n----------------------------------------------------------------------<br />";
$lang_email_notification_pt3       = "de la part de";
$lang_email_notification_pt4       = "\n----------------------------------------------------------------------<br />\n\nCe courrier vient de Pixelpost<br />";
$lang_email_notificationplain_pt1  = "Bonjour,\nUn nouveau commentaire sur votre photoblog !";
$lang_email_notificationplain_pt2  = "\n\nLe commentaire  :\n\n----------------------------------------------------------------------";
$lang_email_notificationplain_pt3  = "de la part de";
$lang_email_notificationplain_pt4  = "\n\n----------------------------------------------------------------------\n\nCe courrier vient de Pixelpost";

// Error Message
$lang_nothing_to_show           = "Revenez bient&ocirc;t, il n'y a pas encore d'image ici !";
// Please do not translate any tags like this one: <TIME_TO_WAIT>
$lang_spamflood					= "Il y a une protection contre les moteurs de spam. Il vous faut attendre <TIME_TO_WAIT> avant de publier un autre commentaire. Merci.";


// RSS & ATOM Feed
$lang_comment_feed_title        = "Les derniers commentaires sur";
$lang_comment_feed_image_title  = "Commentaire &agrave; propos de";

// end of french language file
?>